### PR TITLE
Include windows version of test

### PR DESCRIPTION
**Pull request by jankatins**
Enjoy... :-) Had to comment out a few versions because they are not available on win or crashed...

### CODE REVIEW

**Comment by hrbrmstr** [comment]
thx. the differences are super-weird IMO. i grok why after read a bit, but it's insane to have to think abt it when trying to get stuff done.

**Comment by jankatins** [comment]
We had to work around the pdf device spitting out unicode errors in IRkernel: https://github.com/IRkernel/IRkernel/issues/336 and then https://github.com/IRkernel/IRkernel/issues/341 ... I think I get it why RStudio has [build their own device](https://github.com/rstudio/rstudio/tree/ebb054efe3e650de818a251b11087311e5169ed8/src/cpp/r/session/graphics)...

**Comment by hrbrmstr** [comment]
aye (though their graphics device is a bit wonky at times, too).

(hate to ask this but you've got Windows more handy :-) can you also try `win.metafile()`? 

btw: R3.3 IRKernel is 👍. It dropped in perfectly on OS X and Linux. It's super handy when I don't really want to add a remote RStudio install to AWS instances and need to keep analyses with GBs of data sets in RAM active and use different clients to get to them across a few days (it sure beats `screen` / `tmux` and a plain R command prompt :-)

**Comment by jankatins** [comment]
see #2

**Comment by jankatins** [comment]
R kernels: thanks! :-)

I do hope that one of the next versions of the notebook will gain remote kernels, there is already some work to enable that :-)

**Pull request merged**
